Repository hyperwallet/hyperwallet-ios-ui-sdk, pull requests merged in 2019-06, with the labels that each got.

#62 HW-52982 Date pickers localization fix
  Sources/Localization/en.lproj/Localizable.strings
  Sources/View/Widget/DateWidget.swift
  Sources/View/Widget/ExpiryDatePickerView.swift
Labels: enhancement

#64 HW-52649 Integer amount value and separator insets fix on Transaction Details
  Sources/Receipt/ReceiptDetailSectionData.swift
  Sources/Receipt/ReceiptDetailTableViewController.swift
  Tests/Receipt/ReceiptDetailPresenterTests.swift
  Tests/Receipt/Responses/UserReceiptDetails.json
Labels: bug

#56 Task/hw 53475 update hyperwallet transfer method
  HyperwalletUISDK.xcodeproj/project.pbxproj
  Sources/TransferMethod/AddTransferMethodPresenter.swift
  Sources/TransferMethod/ListTransferMethodPresenter.swift
  Tests/TransferMethod/AddTransferMethodPresenterTests.swift
  Tests/TransferMethod/Responses/WireAccountIndividualResponse.json
  UITests/BaseTests/BaseTest.swift
  UITests/Helper/HyperwalletMockWebServer.swift
  UITests/Helper/TransferMethod/AddTransferMethod.swift
  UITests/Responses/TransferMethod/Business/TransferMethodConfigurationKeysBusinessResponse.json
  UITests/Responses/TransferMethod/Business/TransferMethodConfigurationWireAccountBusinessResponse.json
  UITests/Responses/TransferMethod/Business/WireAccountBusinessResponse.json
  UITests/Responses/TransferMethod/Individual/TransferMethodConfigurationWireAccountResponse.json
  UITests/Responses/TransferMethod/Individual/WireAccountIndividualResponse.json
  UITests/TransferMethod/AddTransferMethodBankAccountIndividualTests.swift
  UITests/TransferMethod/AddTransferMethodWireAccountBusinessTests.swift
  UITests/TransferMethod/AddTransferMethodWireAccountIndividualTests.swift
Labels: enhancement

#60 Task/hw 53264 add ui test transaction details
  HyperwalletUISDK.xcodeproj/project.pbxproj
  UITests/Helper/Receipts/TransactionDetails.swift
  UITests/Receipts/ListReceiptTests.swift
  UITests/Receipts/TransactionDetailTests.swift
  UITests/Responses/Receipts/ReceiptsForOneMonth.json
Labels: UI test

#58 HW-52979 UI - List Receipts Prepaid Card
  Cartfile.resolved
  Demo/ViewController.swift
  HyperwalletUISDK.xcodeproj/project.pbxproj
  README.md
  Sources/HyperwalletUI.swift
  Sources/Receipt/ListReceiptTableViewController.swift
  Sources/Receipt/ListReceiptViewPresenter.swift
  Tests/Receipt/ListReceiptPresenterTests.swift
  Tests/Receipt/Responses/PrepaidCardReceiptResponse.json
  UITests/Receipts/ListReceiptTests.swift
  UITests/Receipts/TransactionDetailTests.swift
Labels: enhancement
