Repository hyperwallet/hyperwallet-ios-ui-sdk, pull requests merged in 2019-07, with the labels that each got.

#66 HW-52981 Fixed left inset on iOS 10.0 iPhone 5plus/6plus in landscape
  Sources/Receipt/ReceiptDetailTableViewController.swift
Labels: bug

#69 Task/hw 53264 update ui tests to use accessibility id transaction details
  HyperwalletUISDK.xcodeproj/project.pbxproj
  UITests/Extensions/XCTestCase.swift
  UITests/Helper/Receipts/TransactionDetails.swift
  UITests/Receipts/ListReceiptTests.swift
  UITests/Receipts/TransactionDetailTests.swift
  UITests/Responses/Receipts/ReceiptsForOneMonth.json
Labels: UI test

#75 HW-54040 Fix long type and amount in list receipt u i
  Sources/Receipt/ReceiptTransactionTableViewCell.swift
  UITests/Receipts/ListReceiptTests.swift
Labels: enhancement

#72 HW-54027 update accessibility id for value fields
  Sources/Receipt/ListReceiptTableViewController.swift
  Sources/Receipt/ReceiptDetailSectionData.swift
  Sources/Receipt/ReceiptDetailTableViewCell.swift
  Sources/Receipt/ReceiptDetailTableViewController.swift
  Sources/Receipt/ReceiptFeeTableViewCell.swift
  Sources/Receipt/ReceiptTransactionTableViewCell.swift
  Sources/View/Widget/AbstractWidget.swift
  Sources/View/Widget/ExpiryDateWidget.swift
  Tests/Receipt/ReceiptDetailPresenterTests.swift
  UITests/Helper/Receipts/TransactionDetails.swift
  UITests/Receipts/ListReceiptTests.swift
Labels: UI test, on hold

#67 Task/hw 53820 add ui tests new list receipts prepaid card
  Demo/Info.plist
  Demo/ViewController.swift
  HyperwalletUISDK.xcodeproj/project.pbxproj
  UITests/Helper/Receipts/TransactionDetails.swift
  UITests/Receipts/ListReceiptTests.swift
  UITests/Receipts/PrepaidCardListReceiptTests.swift
  UITests/Responses/Receipts/PrepaidCardReceiptsForFewMonths.json
  UITests/Responses/Receipts/PrepaidCardReceiptsForOneMonth.json
  UITests/Responses/Receipts/PrepaidCardReceiptsPaging.json
  UITests/TransferMethod/AddTransferMethodBankAccountIndividualTests.swift
Labels: UI test

#81 HW-54045 Add inset separator in receipt details
  Sources/Receipt/ReceiptDetailTableViewController.swift
Labels: enhancement

#80 HW-53971 Swift upgrade to version 5
  .travis.yml
  Cartfile
  HyperwalletUISDK.podspec
  HyperwalletUISDK.xcodeproj/project.pbxproj
  README.md
  Sources/View/ProcessingView/ProcessingView.swift
Labels: Revert carthage file, enhancement

#90 Bugfix/hw 54454 business account when server return error for intermediary bic info relationship row becomes empty
  HyperwalletUISDK.xcodeproj/project.pbxproj
  Sources/TransferMethod/AddTransferMethodTableViewController.swift
  Tests/Helper/HyperwalletTestHelper.swift
  Tests/TransferMethod/AddTransferMethodPresenterTests.swift
  Tests/TransferMethod/Responses/UnexpectedErrorResponse.json
Labels: bug

#98 Hotfix - Fixed after merge
  Sources/TransferMethod/ListTransferMethodPresenter.swift
  Tests/TransferMethod/AddTransferMethodPresenterTests.swift
Labels: bug

#85 Task/HW-54259 create transfer method repository
  .slather.yml
  Cartfile.private
  Cartfile.resolved
  HyperwalletUISDK.xcodeproj/project.pbxproj
  HyperwalletUISDK.xcodeproj/xcshareddata/xcschemes/HyperwalletUISDK.xcscheme
  HyperwalletUISDK.xcodeproj/xcshareddata/xcschemes/TransferMethodRepository.xcscheme
  Sources/Receipt/ListReceiptViewPresenter.swift
  Sources/TransferMethod/AddTransferMethodPresenter.swift
  Sources/TransferMethod/AddTransferMethodTableViewController.swift
  Sources/TransferMethod/ListTransferMethodPresenter.swift
  Sources/TransferMethod/SelectTransferMethodTypePresenter.swift
  Tests/TransferMethod/AddTransferMethodPresenterTests.swift
  Tests/TransferMethod/Responses/BankAccountErrorResponseWithMissingField.json
  Tests/TransferMethod/Responses/BankAccountErrorResponseWithValidationError.json
  Tests/TransferMethod/Responses/BankAccountIndividualResponse.json
  TransferMethodRepository/Sources/Helper/CompletionHelper.swift
  TransferMethodRepository/Sources/TransferMethodRepository.swift
  TransferMethodRepository/Sources/TransferMethodRepositoryFactory.swift
  TransferMethodRepository/Tests/RemoteTransferMethodConfigurationRepositoryTests.swift
  TransferMethodRepository/Tests/TransferMethodRepositoryFactoryTests.swift
  TransferMethodRepository/Tests/TransferMethodRepositoryTests.swift
Labels: enhancement

#102 HW-51600 Fixed alignment of the searchBar placeholder (iOS 10.0-10.3)
  Common/Sources/Extensions/UISearchBar.swift
  Common/Sources/Generics/GenericController.swift
  HyperwalletUISDK.xcodeproj/project.pbxproj
  UITests/Helper/TransferMethod/SelectTransferMethodType.swift
Labels: bug

#105 Updated UI SDK for optional changes, in core sdk for model class.
  Common/Sources/Extensions/HyperwalletCountry.swift
  Common/Sources/Extensions/HyperwalletCurrency.swift
  Common/Sources/Extensions/HyperwalletFee.swift
  Common/Sources/Generics/GenericCell.swift
  Receipt/Sources/ListReceiptPresenter.swift
  Receipt/Sources/ReceiptDetailSectionData.swift
  Receipt/Sources/ReceiptTransactionCell.swift
  Receipt/Tests/ListReceiptPresenterTests.swift
  Receipt/Tests/ReceiptDetailPresenterTests.swift
  ReceiptRepository/Tests/PrepaidCardReceiptRepositoryTests.swift
  ReceiptRepository/Tests/UserReceiptRepositoryTests.swift
  TransferMethod/Sources/CountryCurrencyCell.swift
  TransferMethod/Sources/SelectTransferMethodTypePresenter.swift
  TransferMethod/Sources/View/Widget/SelectionWidget.swift
  TransferMethodRepository/Tests/TransferMethodRepositoryTests.swift
  UITests/Receipts/PrepaidCardListReceiptTests.swift
Labels: Revert carthage file

#117 Added select destination feature
  Common/Sources/Extensions/HyperwalletTransferMethod.swift
  Common/Sources/Localization/en.lproj/Localizable.strings
  Transfer/Sources/CreateTransferController.swift
  Transfer/Sources/CreateTransferPresenter.swift
  Transfer/Sources/TransferDestinationCell.swift
  TransferMethod/Sources/ListTransferMethodCell.swift
Labels: enhancement

#118 Added Tests to showSelectDestinationAccountView() Method
  HyperwalletUISDK.xcodeproj/project.pbxproj
  Transfer/Tests/CreateTransferPresenterTests.swift
  Transfer/Tests/Helper/TransferMethodRepositoryRequestHelper.swift
  Transfer/Tests/Responses/UnexpectedErrorResponse.json
Labels: enhancement
