Repository hyperwallet/hyperwallet-ios-ui-sdk, pull requests merged in 2020-11, with the labels that each got.

#270 feature/DTSERWTHRE-240-localization-content-updated all the content required for GA
  Common/Sources/Localization/en.lproj/Localizable.strings
  UITests/Receipts/ListAllReceiptsTests.swift
  UITests/Receipts/PrepaidCardListReceiptTests.swift
  UITests/TransferFunds/TransferUserFundsConfirmationTest.swift
  UITests/TransferFunds/TransferUserFundsPPCTest.swift
  UITests/TransferFunds/TransferUserFundsTest.swift
  UITests/TransferMethod/AddTransferMethodBankAccountBusinessTests.swift
  UITests/TransferMethod/AddTransferMethodPayPalAccountTests.swift
  UITests/TransferMethod/ListTransferMethodTests.swift
Labels: Ready To Merge

#265 Task/dtserwthre 21 transactions screen add ui tests for receipt ui
  HyperwalletUISDK.xcodeproj/project.pbxproj
  UITests/Helper/Receipts/TransactionDetails.swift
  UITests/Receipts/ListAllReceiptsTests.swift
  UITests/Responses/Receipts/PrepaidCardSecondaryResponse.json
Labels: Ready To Merge

#268 Feature/dtserwthre 85 prepare translation for transfer to bank card
  Common/Sources/Localization/en.lproj/Localizable.strings
  UITests/Receipts/ListReceiptTests.swift
  UITests/Responses/Receipts/ReceiptsForOneMonth.json
Labels: Ready To Merge, Ready To Test

#271 Added AdaptivePresentationControllerDelegate for controllers.
  Common/Sources/Extensions/UIViewController.swift
  Receipt/Sources/ListReceiptController.swift
  Transfer/Sources/CreateTransferController.swift
  TransferMethod/Sources/AddTransferMethodController.swift
  TransferMethod/Sources/ListTransferMethodController.swift
  TransferMethod/Sources/SelectTransferMethodTypeController.swift
  UITests/TransferMethod/AddTransferMethodBankAccountBusinessTests.swift
Labels: Ready To Test

#273 issue Fixed for footer text margin
  Transfer/Sources/View/TransferTableViewFooterView.swift
Labels: Ready To Merge

#274 DTSERWTHRE-272: Confirm Transfer - Display currency formatting for supported currencies
  Transfer/Sources/Helper/TransferAmountCurrencyFormatter.swift
  Transfer/Sources/ScheduleTransferSectionData.swift
  UITests/TransferFunds/TransferUserFundsConfirmationTest.swift
Labels: Ready To Test

#276 Bugfix/dtserwthre 232 wrap truncated headers
  Common/Sources/Helper/Theme.swift
  Common/Sources/Helper/ThemeManager.swift
Labels: Ready To Test

#279 Bugfix/dtserwthre 232 wrap truncated headers
  Common/Sources/Helper/Theme.swift
Labels: Ready To Merge
