Repository hyperwallet/hyperwallet-ios-ui-sdk, pull requests merged in 2020-12, with the labels that each got.

#280 Added Chinese Traditional translation files
  Common/Sources/Localization/zh-Hant-CN.lproj/Localizable.strings
  Demo/zh-Hant-CN.lproj/LaunchScreen.strings
  Demo/zh-Hant-CN.lproj/Main.strings
  HyperwalletUISDK.xcodeproj/project.pbxproj
  UITests/TransferMethod/AddTransferMethodBankAccountIndividualTests.swift
Labels: Ready To Merge

#277 Transaction tab constrains updated.
  Common/Sources/Extensions/UIView.swift
  Receipt/Sources/ListReceiptController.swift
  UITests/TransferMethod/AddTransferMethodBankAccountIndividualTests.swift
  UITests/TransferMethod/formatting/AddTransferMethodWireAccountUSMaskingTests.swift
Labels: Ready To Merge, Ready To Test

#281 Feature/dtserwthre 270 papercheck uisdk
  Cartfile
  Common/Sources/Extensions/HyperwalletTransferMethod.swift
  Common/Sources/Helper/HyperwalletIcon.swift
  Common/Tests/Extensions/HyperwalletTransferMethodTests.swift
  HyperwalletUISDK.xcodeproj/project.pbxproj
  Transfer/Sources/ScheduleTransferController.swift
  Transfer/Tests/Responses/ListTransferMethodSuccessResponse.json
  TransferMethod/Sources/AddTransferMethodPresenter.swift
  TransferMethod/Sources/ListTransferMethodController.swift
  TransferMethod/Tests/AddTransferMethodPresenterTests.swift
  TransferMethod/Tests/ListTransferMethodPresenterTests.swift
  TransferMethod/Tests/Responses/ListTransferMethodSuccessResponse.json
  TransferMethod/Tests/Responses/PapercheckAccountResponse.json
  TransferMethodRepository/Sources/TransferMethodRepository.swift
  TransferMethodRepository/Tests/Responses/ListTransferMethodSuccessResponse.json
  TransferMethodRepository/Tests/Responses/PapercheckAccountResponse.json
  TransferMethodRepository/Tests/TransferMethodRepositoryTests.swift
  UITests/Helper/TransferMethod/AddTransferMethod.swift
  UITests/Helper/TransferMethod/ListTransferMethods.swift
  UITests/Receipts/ListReceiptTests.swift
  UITests/Responses/Receipts/PaperCheckReceiptsForFewMonths.json
  UITests/Responses/TransferMethod/ListTransferMethodResponsePaperCheck.json
  UITests/Responses/TransferMethod/ListTransferMethodResponseWithoutPaperCheck.json
  UITests/Responses/TransferMethod/TransferMethodCreatePaperCheck.json
  UITests/Responses/TransferMethod/TransferMethodPaperCheckList.json
  UITests/Responses/TransferMethod/TransferMethodPaperCheckResponse.json
  UITests/TransferMethod/AddTransferMethodPaperCheckAccountTests.swift
  UITests/TransferMethod/ListTransferMethodTests.swift
Labels: Ready To Test

#283 Update Transfer Method UI Design
  Demo/ViewController.swift
  TransferMethod/Sources/UpdateTransferMethodController.swift
  TransferMethod/Sources/UpdateTransferMethodSectionData.swift
  TransferMethod/Sources/View/Widget/SelectionWidget.swift
  TransferMethod/Tests/Responses/BankCardUpdateResponse.json
  TransferMethod/Tests/Responses/PayPalUpdateResponse.json
Labels: Ready To Test

#287 bugfix/DTSERWTHRE-297-sourcekitten-issue
  .travis.yml
Labels: Ready To Merge

#288 Feature/dtserwthre 306 update transfer method configuration field query
  TransferMethod/Sources/Extensions/HyperwalletTransferMethodUI.swift
  TransferMethod/Sources/SelectTransferMethodTypeController.swift
  TransferMethod/Tests/Responses/TransferMethodConfigurationFieldsResponse.json
  TransferMethodRepository/Tests/Responses/TransferMethodConfigurationFieldsOnlyPaypalAccountUsResponse.json
  TransferMethodRepository/Tests/Responses/TransferMethodConfigurationFieldsResponse.json
  UITests/Helper/TransferFunds/TransferFunds.swift
  UITests/Helper/TransferMethod/AddTransferMethod.swift
  UITests/Responses/TransferMethod/Individual/TransferMethodConfigrationUSBankAccountResponseMask.json
  UITests/Responses/TransferMethod/Individual/TransferMethodConfigurationBankAccountResponse.json
  UITests/Responses/TransferMethod/Individual/TransferMethodConfigurationResponseWithStarMasks.json
  UITests/Responses/TransferMethod/Individual/TransferMethodConfigurationUSBankCardResponseWithMask.json
  UITests/Responses/TransferMethod/Individual/TransferMethodConfigurationWireAccountResponseWithMask.json
  UITests/Responses/TransferMethod/TransferMethodConfigurationBankAccountBusinessResponse.json
  UITests/Responses/TransferMethod/TransferMethodConfigurationBankAccountResponse.json
  UITests/Responses/TransferMethod/TransferMethodConfigurationBankCardResponse.json
  UITests/Responses/TransferMethod/TransferMethodConfigurationPayPalAccountResponse.json
  UITests/Responses/TransferMethod/TransferMethodConfigurationWireAccountResponse.json
  UITests/Responses/TransferMethod/TransferMethodPaperCheckResponse.json
  UITests/Responses/TransferMethod/TransferMethodVenmoResponse.json
Labels: Ready To Merge

#284 DTSERWTHRE221 - Code updated for Transfer zero fund issue fix
  Common/Sources/Localization/en.lproj/Localizable.strings
  HyperwalletUISDK.xcodeproj/project.pbxproj
  Transfer/Sources/CreateTransferPresenter.swift
  Transfer/Sources/TransferAllFundsCell.swift
  Transfer/Tests/CreateTransferPresenterTests.swift
  UITests/Helper/TransferFunds/TransferFunds.swift
  UITests/Responses/TransferFunds/TransferErrorMaxThresholdExceed.json
  UITests/TransferFunds/TransferUserFundsPPCTest.swift
  UITests/TransferFunds/TransferUserFundsTest.swift
Labels: Ready To Merge
